package com.mycompany.gran_mineria.BuscarStrategy;

import com.mycompany.gran_mineria.*;
import static com.mycompany.gran_mineria.ControladoraMinas.mapaRegiones;
import static com.mycompany.gran_mineria.GranMineria.Alertamsj;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class BuscarPorRango extends javax.swing.JFrame implements BuscarStrategy, LimpiadorVentanas {

    public BuscarPorRango() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        limiteInfLabel = new javax.swing.JLabel();
        limiteInfTextField = new javax.swing.JTextField();
        limiteSupLabel = new javax.swing.JLabel();
        limiteSupTextField = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        limpiarButton = new javax.swing.JButton();
        volverButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        limiteInfLabel.setText("Limite inferior");

        limiteSupLabel.setText("Limite superior");

        limiteSupTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limiteSupTextFieldActionPerformed(evt);
            }
        });

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla);

        limpiarButton.setText("Limpiar tabla");
        limpiarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarButtonActionPerformed(evt);
            }
        });

        volverButton.setText("Volver");
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(limiteSupLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(limiteInfLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(limiteSupTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(limiteInfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(limpiarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(limiteInfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(limiteInfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(limiteSupLabel)
                            .addComponent(limiteSupTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(limpiarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(volverButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limiteSupTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limiteSupTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limiteSupTextFieldActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        mostrarEnGUI();

    }//GEN-LAST:event_buscarButtonActionPerformed
    //LIMPIA LA VISTA DE LA VENTANA
    private void limpiarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) Tabla.getModel();
        model.setRowCount(0);
        limpiarVista();
    }//GEN-LAST:event_limpiarButtonActionPerformed
    //CIERRA LA VENTANA
    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        dispose();
    }//GEN-LAST:event_volverButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarPorRango.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarPorRango.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarPorRango.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarPorRango.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarPorRango().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton buscarButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel limiteInfLabel;
    private javax.swing.JTextField limiteInfTextField;
    private javax.swing.JLabel limiteSupLabel;
    private javax.swing.JTextField limiteSupTextField;
    private javax.swing.JButton limpiarButton;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void limpiarVista() {
        limiteInfTextField.setText("");
        limiteSupTextField.setText("");
    }
    
    public Object obtenerDatosBuscados(String key){
        return null;
    }
    // METODO ENCARGADO DE MOSTRAR LAS MINAS DENTRO DE UN RANGO
    public void mostrarEnGUI(){
        int limiteInf, limiteSup;
        limiteInf = Integer.parseInt(limiteInfTextField.getText());
        limiteSup = Integer.parseInt(limiteSupTextField.getText());
        if(limiteSup < limiteInf){
            Alertamsj("Ingrese nuevamente los limites, limite inferior no debe ser mas grande que el limite superior ", "Gran Mineria");
            limpiarVista();
        }
        DefaultTableModel model = (DefaultTableModel) Tabla.getModel();
        Object rowData[] = new Object[4];
        Iterator<Map.Entry<String, Pais>> entriesPa = ControladoraMinas.mapaPaises.entrySet().iterator();
        Iterator<Map.Entry<String, Region>> entriesReg = ControladoraMinas.mapaRegiones.entrySet().iterator();
        while (entriesPa.hasNext()) {
            Map.Entry<String, Pais> entry = entriesPa.next();
            Pais paux=entry.getValue();
            ArrayList<Region> list= entry.getValue().getlistaRegiones();
            while (entriesReg.hasNext()){
                Map.Entry<String, Region> entryReg = entriesReg.next();
                int i;
                for(i=0; i<list.size();i++){
                    ArrayList<Minas> minas=list.get(i).getlistaMinas();
                    int j;
                    for(j=0; j<minas.size();j++){
                        if(limiteInf<= minas.get(i).getProduccion() && minas.get(i).getProduccion() <=limiteSup){
                                rowData[0] =  minas.get(i).getNombre();
                                rowData[1] =  minas.get(i).getMineral();
                                rowData[2] =  minas.get(i).getProduccion();
                                rowData[3] =  minas.get(i).getPersonal();
                                model.addRow(rowData);
                        }
                    }
                    
                }
            }
        }
        
        /*
        mapaRegiones.values().stream().map(value -> value.getlistaMinas()).forEachOrdered(lista -> {
            for (int i = 0; i<lista.size(); i++){
                Minas mina = (Minas)lista.get(i);
                int produccion= mina.getProduccion();
                if (limiteInf<= produccion && produccion <=limiteSup){
                    rowData[0] =  mina.getNombre();
                    rowData[1] =  mina.getMineral();
                    rowData[2] =  mina.getProduccion();
                    rowData[3] =  mina.getPersonal();
                    model.addRow(rowData);
                }
            }
        });*/
    }
}
